env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
parserOptions:
  ecmaVersion: latest
plugins:
  - html
rules: 
  no-console: error
  no-unused-vars:
    - error
    - argsIgnorePattern: ^_
